server:
    port: 18080

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/inventria?autoReconnect=true&useSSL=false
    username: root
    password: Damilola1979!@#
    tomcat:
            test-while-idle: true
            validation-query: SELECT 1
  jpa:
    hibernate:
        ddl-auto: 'update '
        naming-strategy: org.hibernate.cfg.DefaultComponentSafeNamingStrategy
    properties:
        hibernate:
            dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
  sql:
    init:
        continue-on-error: true
        data-locations: data-mysql.sql
        platform: mysql
        schema-locations: schema-mysql.sql